name: animalxref
description: An Animal Crossing New Horizons fish reference web application built with Flutter Web.

version: 1.0.0+1

environment:
  sdk: ">=2.7.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1

flutter:
  uses-material-design: true
