name: animalxref
description: An Animal Crossing New Horizons fish reference web application built with Flutter Web.

version: 1.16.4

environment:
  sdk: ">=2.7.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.1.2
  backup: 
    path: backup
  intl: ^0.16.1
  provider: ^4.3.2+3
  shared_preferences: ^0.5.12+4

flutter:
  uses-material-design: true

  assets:
    - assets/bugs.json
    - assets/creatures.json
    - assets/fish.json
