name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.flutter_web}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git clone beta https://github.com/flutter/flutter.git $HOME/flutter
          export PATH="$PATH:$HOME/flutter/bin"
          flutter config --enable-web
          flutter build web
      - run: |
          cd build/web
          git init
          git config --global user.email brianji03gmail.com
          git config --global user.name "Brian Isganitis"
          git status
          git remote add origin https://${{secrets.flutter_web}}@github.com/brianji/animalxref.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Update GitHub pages"
          git push origin gh-pages -f
